path = File.expand_path('../', __FILE__)
require File.join(path, 'lib/client.rb')
require File.join(path, 'lib/dialogue.rb')
require File.join(path, 'lib/command.rb')
require File.join(path, 'lib/get_talk.rb')
require File.join(path, 'lib/get_user_recent.rb')
